### ISSUE TITLE
PLUGIN NOT ACTIVATED

### ISSUE THREAD

**Issue by hardsiamang655** [BeanGTA/ASkyBlock-Remastered-NukkitPM1E#1]
17:14:12 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/json/JSONObject
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [Nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [Nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [Nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/json/JSONObject
        at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.<init>(SchematicHandler.java:422) ~[?:?]
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?]
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.<init>(SchematicHandler.java:422) ~[?:?]
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?]
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
17:14:12 [INFO ] Disabling ASkyBlock v0.5.2-BETA

**Comment by TienIC** [comment]
> 17:14:12 [ERROR] Throwing java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/json/JSONObject at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [Nukkit.jar:?] at cn.nukkit.Server.enablePlugin(Server.java:750) [Nukkit.jar:?] at cn.nukkit.Server.enablePlugins(Server.java:739) [Nukkit.jar:?] at cn.nukkit.Server.(Server.java:582) [Nukkit.jar:?] at cn.nukkit.Nukkit.main(Nukkit.java:120) [Nukkit.jar:?] Caused by: java.lang.NoClassDefFoundError: org/json/JSONObject at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?] at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?] at com.larryTheCoder.schematic.SchematicHandler.(SchematicHandler.java:422) ~[?:?] at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?] at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?] at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?] at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?] at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?] ... 4 more Caused by: java.lang.ClassNotFoundException: org.json.JSONObject at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?] at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Nukkit.jar:?] at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?] at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?] at com.larryTheCoder.schematic.SchematicHandler.(SchematicHandler.java:422) ~[?:?] at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?] at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?] at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?] at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?] at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?] ... 4 more 17:14:12 [INFO ] Disabling ASkyBlock v0.5.2-BETA

Are you using NukkitPM1 or Nukkit Original?

**Comment by hardsiamang655** [comment]
yes

**Comment by TienIC** [comment]
> yes

What ?

**Comment by hardsiamang655** [comment]
Im using pm1 edition

**Comment by TienIC** [comment]
> Im using pm1 edition

Can you describe how it fails?

**Comment by hardsiamang655** [comment]
The plugin does not open. And in the latest version I can't add partners to the island. Only 1 version works fine and has no source code.

**Comment by TienIC** [comment]
> The plugin does not open. And in the latest version I can't add partners to the island. Only 1 version works fine and has no source code.

What is the latest version and the version without the source code? Also, what java version are you using?

**Comment by hardsiamang655** [comment]
I'm using Java 1.8. Working version is 0.4.8, in others I can't add partners to the island.

**Comment by TienIC** [comment]
> I'm using Java 1.8. Working version is 0.4.8, in others I can't add partners to the island.

okay, I'll try to find the error. Version 0.5.0 dumped up has a lot of redundant code that is not omitted. More not yet completed. To re-optimize, I will remove all redundant features.

**Comment by hardsiamang655** [comment]
A plugin that I can add partner to the island would be great.
